function Hd = dofilter_test
%DOFILTER_TEST 이산시간 필터 객체를 반환합니다.

% MATLAB Code
% Generated by MATLAB(R) 9.5 and DSP System Toolbox 9.7.
% Generated on: 20-Dec-2019 16:52:15

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 5000;  % Sampling Frequency

Fstop1 = 247;    % First Stopband Frequency
Fpass1 = 259;    % First Passband Frequency
Fpass2 = 263;    % Second Passband Frequency
Fstop2 = 275;    % Second Stopband Frequency
Dstop1 = 0.001;  % First Stopband Attenuation
Dpass  = 0.1;    % Passband Ripple
Dstop2 = 0.001;  % Second Stopband Attenuation
dens   = 20;     % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
